Hide help block on dashboard
banocean/ifv pull request #10
Opened 2024-08-28 19:18 UTC by majusss

Looks very irritating to me
![image](https://github.com/user-attachments/assets/25ca06e8-d676-4141-a79c-cefe6a419484)

2024-08-28 19:37 UTC, PanLiszka approved these changes
Looks good to me!

2024-08-28 19:38 UTC, banocean requested changes

2024-08-28 19:38 UTC, banocean commented on apply.js
> +    description: "Hide irritating blue help block on dashboard",
It's blue only in eduVULCAN, Dziennik Vulcan has it red. Also, I'd descriptions to not be as opinionated.

2024-08-29 11:56 UTC, banocean requested changes

2024-08-29 11:56 UTC, banocean commented on apply.js
> +    description: "Hide help block on dashboard.",
```suggestion
description: "Hides \"Do you need help\" tile",
```

2024-08-29 13:43 UTC, merged