More readable navigation for mobile
banocean/ifv pull request #25
Opened 2024-08-31 13:22 UTC by banocean

2024-08-31 21:03 UTC, PanLiszka requested changes
![image](https://github.com/user-attachments/assets/fd4b2429-b603-4f04-9cfe-f9fb3ba991f7)
![image](https://github.com/user-attachments/assets/f247866d-6618-4a91-a61f-4b8ac794d870)
![opera_w8bdyS0lfk](https://github.com/user-attachments/assets/655acd3b-3e01-4d1c-85d6-15601ffda63b)
![opera_HJUkcpI9c3](https://github.com/user-attachments/assets/519380af-e852-4567-8b28-989426dadfb8)

2024-08-31 22:07 UTC, wozniaczek123 requested changes

2024-08-31 22:55 UTC, banocean commented on patches/newMobileNavbar/styles.css
This will be a lot of work :sweat:

2024-09-01 18:37 UTC, PanLiszka approved these changes

2024-09-01 18:43 UTC, merged