Move user dropdown options to modal
banocean/ifv pull request #36
Opened 2024-09-01 18:45 UTC by PanLiszka

- added moveUserOptionsToHeader patch

2024-09-01 18:51 UTC, banocean commented on apply.js
> -    allowedHostsCss: ["uczen.eduvulcan.pl", "dziennik-uczen.vulcan.net.pl"],
I don't think this change was supposed to be there

2024-09-01 19:59 UTC, banocean commented on patches/moveUserOptionsToHeader/script.js
> +    /* Close Aside */
tbh code here is self-explanatory

2024-09-01 20:10 UTC, banocean requested changes
![image](https://github.com/user-attachments/assets/3043b5f7-2315-41c3-b0ce-2e9dd88e968d)
this doesn't look like it should

2024-09-01 20:10 UTC, banocean commented on patches/moveUserOptionsToHeader/script.js
since there is no action added to the links, it refreshes the website

2024-09-03 06:12 UTC, banocean requested changes
Breaks bottom navigation

2024-09-13 16:48 UTC, banocean requested changes
formatting is missing

2024-09-13 16:48 UTC, banocean commented on patches.json
This for sure is out of date and only doesn't conflict because everything is overwritten

2024-09-13 17:04 UTC, Marioneq4958 submitted a review, later dismissed
It looks good, I'll test it immediately.

2024-09-15 07:28 UTC, banocean approved these changes

2024-09-15 13:06 UTC, rotkiW285 approved these changes
LGTM

2024-09-15 13:06 UTC, rotkiW285 approved these changes

2024-09-15 15:59 UTC, PanLiszka commented on patches/moveUserOptionsToHeader/styles.css
> +        background: #38817f !important;
![opera_MuXJ8p2wOT](https://github.com/user-attachments/assets/e5ad326f-b2d1-4edf-83dc-e5ee35e6dde4)

Text on avatar should be white

2024-09-15 15:59 UTC, PanLiszka commented on patches/moveUserOptionsToHeader/styles.css
> +        background: #38817f !important;
```suggestion
        background: #38817f !important;
        color: #ffffff;
```

2024-09-15 22:00 UTC, banocean approved these changes

2024-09-15 22:00 UTC, merged