(patch): showing login and password fields together
banocean/ifv pull request #69
Opened 2024-09-13 19:01 UTC by Marioneq4958

closes: #66

2024-09-13 19:05 UTC, Marioneq4958 commented
Dziennik logowanie:
![Zrzut ekranu z 2024-09-13 o 21 04 47](https://github.com/user-attachments/assets/28479e0b-8884-4d86-a2e4-4ceb5e75f55f)

eduVULCAN:
![Zrzut ekranu z 2024-09-13 o 21 05 33](https://github.com/user-attachments/assets/38c1b193-3462-4936-8677-9703823d006c)

2024-09-13 19:07 UTC, banocean requested changes
Doesn't hide "Krok 1 z 2" as visible in https://github.com/banocean/ifv/pull/69#issuecomment-2349952827

2024-09-13 19:09 UTC, banocean commented
> closes: #66

I think it closes https://github.com/banocean/ifv/issues/43 as well

2024-09-13 19:11 UTC, Marioneq4958 commented
> Doesn't hide "Krok 1 z 2" as visible in [#69 (comment)](https://github.com/banocean/ifv/pull/69#issuecomment-2349952827)

Fixed

![Zrzut ekranu](https://github.com/user-attachments/assets/50fe32ac-1d03-48dd-a103-555486115067)

2024-09-13 19:58 UTC, banocean requested changes
input should have `autocompleate` attribute to help password managers that work based on official standards instead of trying to find information based on their own

2024-09-13 19:58 UTC, banocean commented on patches/loginPasswordTogether/moveLinksEV.js
![image](https://github.com/user-attachments/assets/db8cc236-68a2-4dc9-834a-da37dc16b2ab)
There is some more stuff that requires same thing

2024-09-13 19:58 UTC, banocean commented on patches.json
Seems to break when you try to submit invalid password (this also triggers captcha to display)
![image](https://github.com/user-attachments/assets/8807b740-5e8d-4f1b-8d37-26abc0ba8e9f)

2024-09-13 19:58 UTC, banocean commented on patches.json
You can even see animation of the input disappearing :sob:

2024-09-13 19:58 UTC, banocean commented on patches.json
Login button redirects me to https://dziennik-logowanie.vulcan.net.pl/warszawazoliborz/Home/Index instead of logging me in

2024-09-15 13:24 UTC, rotkiW285 requested changes
My password manager (bitwarden) still does not autocomplete login in dziennik vulcan (chrome password manager works)

2024-09-15 21:59 UTC, banocean commented
> My password manager (bitwarden) still does not autocomplete login on pc in dziennik vulcan (chrome password manager works).

Firefox password manager autocomplete works only with password input, login is still not detected for me 😦

2024-09-25 19:31 UTC, PanLiszka approved these changes
U mnie działa

2024-09-25 19:45 UTC, rotkiW285 commented
Domyślny menadżer haseł firefox wciąż nie widzi inputu hasło na `dziennik-logowanie.vulcan.net.pl`. Bitwarden tak jak nie uzupełniał loginu tak wciąż tego nie robi. Menadżer haseł chrome i cała strona eduvulcan działają perfekcyjnie

2024-09-25 20:03 UTC, banocean approved these changes

2024-09-25 20:03 UTC, rotkiW285 approved these changes
LGTM

2024-09-25 20:04 UTC, merged