Hide subjects with no grades
banocean/ifv pull request #71
Opened 2024-09-17 07:46 UTC by banocean

2024-09-25 17:40 UTC, PanLiszka requested changes

2024-09-25 17:40 UTC, PanLiszka commented on patches/hideSubjectsWithNoGrades/script.js
> +        if (!predictedFinalGrade.querySelector(".info-text > span")?.innerText?.trim()) {
![image](https://github.com/user-attachments/assets/3c8dead1-5882-47fe-a714-f4322c234197)

```suggestion
        if (!predictedFinalGrade?.querySelector(".info-text > span")?.innerText?.trim()) {
```

2024-09-25 17:56 UTC, PanLiszka requested changes

2024-09-25 17:56 UTC, PanLiszka commented on patches/hideSubjectsWithNoGrades/script.js
> +        const finalGrades = document.querySelector(".tile__content:last-of-type")
This should point to the `subject` not to whole document

```suggestion
        const finalGrades = subject.querySelector(".tile__content:last-of-type")
```

2024-09-26 19:50 UTC, rotkiW285 approved these changes
It works, LGTM

2024-09-26 20:05 UTC, jezyq14 approved these changes

2024-09-26 20:10 UTC, merged