Redirect to board
banocean/ifv pull request #8
Opened 2024-08-27 17:59 UTC by PanLiszka

- Added redirectToBoard patch

2024-08-27 19:07 UTC, banocean requested changes

2024-08-27 19:07 UTC, banocean commented on patches/redirectToBoard.js
> +        const url = !!window.location.hostname.match(
two times checked for the same thing and still adding 2nd option that isn't even possible

2024-08-27 19:07 UTC, banocean commented on patches/redirectToBoard.js
> +        characterData: true,
why?

2024-08-27 19:07 UTC, banocean commented on patches/redirectToBoard.js
> +        attributes: true,
also why?

2024-08-27 19:25 UTC, banocean requested changes

2024-08-27 19:31 UTC, PanLiszka reviewed
you haven't seen it, ok?

2024-08-27 19:32 UTC, PanLiszka commented on patches/redirectToBoard/script.js
> +    document.querySelector(".header__logo-product").firstChild;
you haven't seen it, ok?

2024-08-28 14:11 UTC, banocean approved these changes
LGTM!

2024-08-28 14:12 UTC, merged